server:
  port: 8080
  context-path: /service #项目访问路径
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/index_data?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    hibernate: 
      ddl-auto: update
    open-in-view: true
logging.level.org.hibernate.SQL: debug
debug: true 